name: upload-release-asset

permissions:
  contents: write  # For accessing the repository contents
  packages: write  # For managing release assets

# Trigger the workflow when a new release is created
on:
  workflow_dispatch:
    inputs:
       environment:
        type: environment

jobs:
  upload:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Print env stuff
        run: echo ${{ secrets.TEST_ENV }}
